-- SET SESSION storage_engine = "InnoDB";
-- SET SESSION time_zone = "+8:00";
-- ALTER DATABASE CHARACTER SET "utf8";

-- CREATE DATABASE IF NOT EXISTS ten_logservice DEFAULT CHARSET utf8mb4;

DROP TABLE IF EXISTS entries;
CREATE TABLE entries(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  author_id VARCHAR(100) NOT NULL REFERENCES authors(name),
  title VARCHAR(512) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  updated VARCHAR(60) NOT NULL
);

DROP TABLE IF EXISTS authors;
CREATE TABLE authors(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL
);